# Overview {.unnumbered}

:::{.callout-note}
##### Learning Goals

After completing this chapter, learners should be able to:

 * Explain why drawing maps by hand is beneficial and when to use this format over digital methods
 * Implement a workflow for drawing maps by hand
 * Design cartographic elements for their maps
 * Find and use reference materials

:::

## Workshop Description

In this workshop, we'll explore drawing maps by hand rather than using digital tools. This skill is useful for helping the designer deeply understand an area, but it is also a method of self-expression. The fact that it can be fun should also not be minimized.

## Materials

The following materials are recommended to fully participate in this workshop:

 * Paper (at least 2 sheets)
 * Pencils
 * A sharpener if you're using a wood pencil
 * Eraser (bigger than the one that comes on the back of your pencil)
 * Pens
 * Colored pencils, marker, or crayons (optional)
 * A device with internet access to look up reference materials
 
Simple, inexpensive materials are fine for this workshop. Notebook or printer paper and the pens and pencils you have on hand will be sufficient to get started. A large eraser is highly recommended.

For those with previous experience working in digital illustration software such as Inkscape or Illustrator, participants may choose to work in these tools rather than traditional pen and paper, but the workshop will not cover how to use these tools.  

## Prerequisites

This is a beginning level workshop. No previous experience is required in either art or map making.
