# Introduction

Drawing maps by hand has a long history. Today, we often rely on technology to create maps, but there are a number of reasons to work with good ol' pencil and paper:

 1. Understand an area in greater depth
 1. Explore cartographic decisions before working with digital tools
 1. Assess knowledge of an area, either by yourself or with a group
 1. Create art
 1. It's fun!
 
Hand-drawn maps have applications as art, in designing board games, and illustrating manuscripts, just to name a few. 

The maps we work on today in this workshop can be of your own design. They can represent a location that currently exists, or you could choose to represent a historical or future place, or one of your own imagination.  Our goal is to practice a technique.






## Citations

Principles of Cartography https://search.library.ucdavis.edu/permalink/01UCD_INST/9fle3i/alma990012753470403126 

General Cartography https://search.library.ucdavis.edu/permalink/01UCD_INST/9fle3i/alma990017827800403126 



## Additional Resource

[Erwin Raisz, cartographer](https://www.raiszmaps.com/about-erwin-j-raisz/)

[Maps By Owen YouTube Channel](https://www.youtube.com/@MapsbyOwen)

[JP Coovert YouTube Channel](https://www.youtube.com/@JPCoovert)

[DiY LandArch YouTube Channel](https://www.youtube.com/@diylandarch)